cmake_minimum_required(VERSION 3.22.0)
project(task2)


add_executable(task2
    task2.cpp
    task2.h
    Figure.cpp
    Figure.h
    Triangle.cpp
    Triangle.h
    RightTriangle.cpp
    RightTriangle.h
    IsoscelesTriangle.cpp
    IsoscelesTriangle.h
    EquilateralTriangle.cpp
    EquilateralTriangle.h
    Quadrilateral.cpp
    Quadrilateral.h
    Rectangle.cpp
    Rectangle.h
    Square.cpp
    Square.h
    Parallelogram.cpp
    Parallelogram.h
    Rhombus.cpp
    Rhombus.h
)
